spring:
  datasource:
    url: jdbc:h2:mem:churchadmin
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    open-in-view: false

logging:
  config: classpath:logback-spring.xml

